version: 0.2

env:
  variables:

    VITE_REACT_APP_API_URL:  "https://pcomel5tnk.execute-api.ap-south-1.amazonaws.com/v1/api/v1"
    VITE_REACT_APP_ENV: "test"
    VITE_REACT_APP_MAKER_CHECKER_API_URL :  "https://8ytxagfe97.execute-api.ap-south-1.amazonaws.com/v1/api/v1/maker-checker"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing YARN dependencies"
      - yarn install --force
      
  pre_build:
    commands:
      - echo "Pre-build phase complete"
      
  build:
    commands:
      - echo "Starting build process"
      - yarn build

  post_build:
    commands:
      - echo "Copying build output to S3 bucket"
      # Copy the entire dist directory to S3
      - aws s3 cp --recursive ./dist s3://test-policy-fe/
      
      # Cache-control for index.html (to ensure fresh loading)
      - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./dist/index.html s3://test-policy-fe/
      
      # CloudFront cache invalidation for critical files
      - aws cloudfront create-invalidation --distribution-id E22914364J90OR --paths /index.html /service-worker.js